---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 1458266102-ZY3ZplwEbeaaanfE3C16baE5QaR5VDuojXmwcRs
:access_token_secret: JsHxsU32CL6n5g4wDVVldeXSqZvzHAN7qMNISTVbhDB9I
